INSERT INTO
    drivers(name, team, nationality, description)
VALUES
    ('Lewis Hamilton', (SELECT teams.id FROM teams WHERE teams.name = 'Mercedes'), 'British', ' Lewis Hamilton is a British racing driver who has established himself as one of the all-time greats in Formula 1. With his exceptional talent, Hamilton has won multiple World Championships and holds numerous records. Known for his smooth driving style and fierce competitiveness, he has been a dominant force for Mercedes, showcasing his speed and racecraft on track.'),
    ('Valtteri Bottas', (SELECT teams.id FROM teams WHERE teams.name = 'Mercedes'), 'Finnish', 'Valtteri Bottas is a Finnish driver who joined Mercedes in 2017 as Lewis Hamiltons teammate. Bottas has shown impressive speed and consistency, securing wins and supporting the teams Constructors Championship successes. With his cool demeanor and strong qualifying performances, he has firmly established himself as a competitive force in Formula 1.'),
    ('Max Verstappen', (SELECT teams.id FROM teams WHERE teams.name = 'Red Bull Racing'), 'Dutch', 'Max Verstappen burst onto the Formula 1 scene as the youngest driver ever to start a race. As a Dutch driver for Red Bull Racing, Verstappen has showcased his exceptional skill and aggressive racing style. With multiple wins and podium finishes, he has established himself as one of the sports most exciting talents, challenging for victories and going head-to-head with the best in the field.'),
    ('Sergio Perez', (SELECT teams.id FROM teams WHERE teams.name = 'Red Bull Racing'), 'Mexican', 'Sergio Perez, hailing from Mexico, has demonstrated his consistency and racecraft throughout his Formula 1 career. Known for his strong tire management and ability to capitalize on race opportunities, Perez has claimed multiple podium finishes. He joined Red Bull Racing in 2021, aiming to provide crucial support to Max Verstappen and contribute to the teams title aspirations.'),
    ('Lando Norris', (SELECT teams.id FROM teams WHERE teams.name = 'McLaren'), 'British', 'Lando Norris, a British driver, made his Formula 1 debut with McLaren in 2019. He has quickly gained recognition for his raw talent and impressive performances on track. With his speed, race intelligence, and engaging personality, Norris has become a fan favorite in the sport, earning podium finishes and showcasing his potential for future success.'),
    ('Daniel Ricciardo', (SELECT teams.id FROM teams WHERE teams.name = 'McLaren'), 'Australian', 'Daniel Ricciardo, an Australian driver, has built a reputation for his infectious smile and bold overtaking maneuvers. Ricciardo spent several seasons with Red Bull Racing before moving to Renault and subsequently joining McLaren in 2021. With his race-winning experience, sharp racecraft, and ability to extract the maximum from his car, Ricciardo is a formidable competitor on the Formula 1 grid.'),
    ('Charles Leclerc', (SELECT teams.id FROM teams WHERE teams.name = 'Ferrari'), 'Monegasque', 'Charles Leclerc, a Monegasque driver, made his mark in Formula 1 with Sauber (now Alfa Romeo Racing) before joining Ferrari in 2019. Leclerc quickly established himself as a rising star, demonstrating his speed, consistency, and fearless driving style. He has secured wins and pole positions, showcasing his potential to lead Ferraris charge and become a future World Champion.'),
    ('Carlos Sainz Jr.', (SELECT teams.id FROM teams WHERE teams.name = 'Ferrari'), 'Spanish', 'Carlos Sainz Jr., a Spanish driver, has shown great promise throughout his Formula 1 career. Starting with Toro Rosso (now AlphaTauri), Sainz showcased his skill and determination, earning a reputation as a consistent points scorer. He moved to McLaren in 2019, where he continued to impress with his speed, racecraft, and ability to deliver strong performances.'),
    ('Fernando Alonso', (SELECT teams.id FROM teams WHERE teams.name = 'Alpine'), 'Spanish', 'Fernando Alonso, a Spanish racing legend, is known for his two World Championships and remarkable racing talent. After a brief hiatus from Formula 1, Alonso made a highly anticipated return in 2021 with Alpine. With his experience, strategic thinking, and relentless drive, Alonso aims to contribute to the teams success and showcase his enduring competitiveness.'),
    ('Esteban Ocon', (SELECT teams.id FROM teams WHERE teams.name = 'Alpine'), 'French', 'Esteban Ocon, a French driver, has steadily progressed in Formula 1, showcasing his potential and skill. Ocon raced for Force India (now Aston Martin) before joining Renault (now Alpine). With his consistent performances and ability to adapt to different race conditions, Ocon aims to establish himself as a consistent point scorer and support Alpines ambitions.'),
    ('Pierre Gasly', (SELECT teams.id FROM teams WHERE teams.name = 'AlphaTauri'), 'French', 'Pierre Gasly, a French driver, made his mark in Formula 1 with Toro Rosso (now AlphaTauri) before briefly joining Red Bull Racing. Gasly then returned to AlphaTauri, where he showcased his talent and secured a remarkable maiden victory at the 2020 Italian Grand Prix. With his tenacity and speed, Gasly aims to continue delivering strong performances on track.'),
    ('Yuki Tsunoda', (SELECT teams.id FROM teams WHERE teams.name = 'AlphaTauri'), 'Japanese', 'Yuki Tsunoda, a Japanese rookie, made his Formula 1 debut with AlphaTauri in 2021. Known for his aggressive driving style and impressive speed, Tsunoda quickly gained attention and became the first Japanese driver to score points on debut since 1995. With his raw talent and determination, Tsunoda aims to make his mark in the sport.'),
    ('Sebastian Vettel', (SELECT teams.id FROM teams WHERE teams.name = 'Aston Martin'), 'German', 'Sebastian Vettel, a German driver and multiple World Champion, has enjoyed immense success in Formula 1. Vettel secured his championships with Red Bull Racing before moving to Ferrari, and in 2021, he joined Aston Martin. With his strategic prowess, experience, and ability to extract the maximum from his car, Vettel aims to contribute to Aston Martins development and success.'),
    ('Lance Stroll', (SELECT teams.id FROM teams WHERE teams.name = 'Aston Martin'), 'Canadian', 'Lance Stroll, a Canadian driver, entered Formula 1 with Williams before joining Racing Point (now Aston Martin). Stroll has showcased his talent with podium finishes and strong performances in challenging conditions. With his speed and determination, Stroll aims to establish himself as a consistent point scorer and contribute to Aston Martins progress.'),
    ('Kimi Räikkönen', (SELECT teams.id FROM teams WHERE teams.name = 'Alfa Romeo Racing'), 'Finnish', 'Kimi Räikkönen, a Finnish driver and former World Champion, is one of Formula 1s most popular figures. Known for his enigmatic personality and "Iceman" nickname, Räikkönen has raced for top teams like Ferrari and currently competes with Alfa Romeo Racing. With his experience, speed, and unwavering focus, Räikkönen continues to be a fan favorite and a respected driver on the grid.'),
    ('Antonio Giovinazzi',(SELECT teams.id FROM teams WHERE teams.name = 'Alfa Romeo Racing'), 'Italian', 'Antonio Giovinazzi, an Italian driver, has showcased his talent with Alfa Romeo Racing. As a Ferrari Academy member, Giovinazzi combines speed and consistency in his performances. With his determination and desire to make his mark, Giovinazzi aims to continue his progress and contribute to the teams success.'),
    ('Mick Schumacher', (SELECT teams.id FROM teams WHERE teams.name = 'Haas'), 'German', 'Mick Schumacher, the son of legendary seven-time World Champion Michael Schumacher, made his Formula 1 debut in 2021 with Haas. As a member of the Ferrari Driver Academy, Mick brings a famous name and a promising skill set to the grid. He has shown his determination and adaptability throughout his career, aiming to carve his own path and honor his familys racing legacy.'),
    ('Nikita Mazepin', (SELECT teams.id FROM teams WHERE teams.name = 'Haas'), 'Russian', 'Nikita Mazepin, a Russian driver, joined Haas in 2021. With a background in Formula 2, Mazepin brings his racing talent and ambition to Formula 1. Known for his aggressive racing style and speed, he aims to make his mark in the sport and contribute to Haas development.'),
    ('George Russell', (SELECT teams.id FROM teams WHERE teams.name = 'Williams'), 'British', 'George Russell, a British driver, made his Formula 1 debut with Williams in 2019. As a Mercedes junior driver, Russell has demonstrated his exceptional skill and potential for future success. Despite his early career struggles with a backmarker team, Russell has showcased his talent during stand-in appearances for Mercedes, raising his profile as a rising star in the sport.'),
    ('Nicholas Latifi', (SELECT teams.id FROM teams WHERE teams.name = 'Williams'), 'Canadian', 'Nicholas Latifi, a Canadian driver, joined Williams in 2020. With a background in Formula 2, Latifi has steadily progressed through the ranks to secure his place in Formula 1. He showcases a determined and disciplined approach to racing, aiming to consistently contribute to Williams performance and showcase his potential.');